name: ci
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: redoc-cli fleet
        uses: seeebiii/redoc-cli-github-action@v10
        with:
          args: 'bundle https://raw.githubusercontent.com/ns1labs/orb/develop/fleet/api/http/openapi.yaml -o docs/api/fleet.html'

      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force
